---
title: "P8105 Homework 5"
author: "Jasmine Niu"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

```{r}
full_df = 
  tibble(
    files = list.files("data/zip_data/"),
    path = str_c("data/zip_data/", files)
  ) %>% 
  mutate(data = map(path, read_csv)) %>% 
  unnest()
```

 

```{r}
tidy_df = 
  full_df %>% 
  mutate(
    files = str_replace(files, ".csv", ""),
    group = str_sub(files, 1, 3)) %>% #start from 1, end at 3
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "outcome",
    names_prefix = "week_") %>% 
  mutate(week = as.numeric(week)) %>% 
  select(group, subj = files, week, outcome)
```

 

```{r}
tidy_df %>% 
  ggplot(aes(x = week, y = outcome, group = subj, color = group)) + 
  geom_point() + 
  geom_path() + 
  facet_grid(~group)
```


## Problem 2

### Describe the raw data

```{r}
homicide_raw = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```



```{r}
homicide_df =
  homicide_raw %>% 
  mutate(
    city_state = str_c(city, ", ", state)
  ) %>% 
  select(-city, -state)

city_df = 
  homicide_df %>%
  group_by(city_state) %>% 
  summarize(
   homicide_total = n(),
   homicide_unsolved = sum((disposition == c("Open/No arrest", "Closed without arrest")))
  ) %>% 
  arrange(desc(homicide_total))

city_df
```



```{r}
baltimore = city_df %>% 
  filter(city_state == "Baltimore, MD")

prop_test_bal = prop.test(baltimore$homicide_unsolved, baltimore$homicide_total) %>% 
  broom::tidy() %>% 
  select(estimate, conf.low, conf.high)

prop_test_bal
```




```{r}
result_df = city_df %>% 
  mutate(
    prop_test = map2(.x = homicide_unsolved, .y = homicide_total, ~ prop.test(.x, .y) %>%
                       broom::tidy())
    ) %>% 
  unnest() %>%
  select(city_state, estimate, conf.low, conf.high)

result_df
```


```{r}
result_df %>%
  mutate(
    city_state = fct_reorder(city_state, estimate)
    ) %>%
  ggplot(aes(x = estimate, y = city_state)) + 
  geom_point() + 
  geom_errorbar(aes(xmin = conf.low, xmax = conf.high))
```



## Problem 3

